[package]
name = "multilayer_perceptron"
version = "0.1.0"
authors = ["flevesqu <flevesqu@student.42.fr>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
rand = "0.6.5"
serde = { version = "1.0.89", features = ["derive"] }

serde_yaml = "0.8.8"